services:
#    didpoule_page.example:
#        class: didpoule\PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    didpoule_page.roles:
        class:  didpoule\PageBundle\Service\RolesHelper
        arguments: ['%security.role_hierarchy.roles%']

    didpoule_page_access_checker:
        class:  didpoule\PageBundle\Service\AccessChecker
        arguments: ['@security.authorization_checker']