<?php

namespace didpoule\PageBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public final function findOneByCategory($category, $slug)
    {
        $qb = $this->createQueryBuilder('p')
            ->innerJoin('p.categories', 'c')
            ->addSelect('c');

        $qb->where('c.title = :cat')
            ->andWhere('p.slug = :slug')
            ->setParameter('cat', $category)
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
